In [57]:
import requests
import io
from bs4 import BeautifulSoup as bs
import pandas as pd
import re

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

1. Start by performing a GET request on the url above and convert the response into a BeautifulSoup object.

In [5]:
response = requests.get('https://realpython.github.io/fake-jobs/', headers=headers)

In [7]:
soup=bs(response.text)

In [8]:
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fake Python
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
 </head>
 <body>
  <section class="section">
   <div class="container mb-5">
    <h1 class="title is-1">
     Fake Python
    </h1>
    <p class="subtitle is-3">
     Fake Jobs for Your Web Scraping Journey
    </p>
   </div>
   <div class="container">
    <div class="columns is-multiline" id="ResultsContainer">
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Senior Python Developer
          </h2>
          <h3 class="subtitle is-6 company">
           Payne, Roberts and Davis
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Stewartbury, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Energy engineer
          </h2>
          <h3 class="subtitle is-6 company">
           Vasquez-Davidson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Christopherville, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Legal executive
          </h2>
          <h3 class="subtitle is-6 company">
           Jackson, Chambers and Levy
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Ericaburgh, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Fitness centre manager
          </h2>
          <h3 class="subtitle is-6 company">
           Savage-Bradley
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          East Seanview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Product manager
          </h2>
          <h3 class="subtitle is-6 company">
           Ramirez Inc
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          North Jamieview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Medical technical officer
          </h2>
          <h3 class="subtitle is-6 company">
           Rogers-Yates
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Davidville, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Physiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Kramer-Klein
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          South Christopher, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Textile designer
          </h2>
          <h3 class="subtitle is-6 company">
           Meyers-Johnson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Jonathan, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Television floor manager
          </h2>
          <h3 class="subtitle is-6 company">
           Hughes-Williams
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Osbornetown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Waste management officer
          </h2>
          <h3 class="subtitle is-6 company">
           Jones, Williams and Villa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Scotttown, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Software Engineer (Python)
          </h2>
          <h3 class="subtitle is-6 company">
           Garcia PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ericberg, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Interpreter
          </h2>
          <h3 class="subtitle is-6 company">
           Gregory and Sons
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ramireztown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Architect
          </h2>
          <h3 class="subtitle is-6 company">
           Clark, Garcia and Sosa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Figueroaview, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Meteorologist
          </h2>
          <h3 class="subtitle is-6 company">
           Bush PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Kelseystad, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Audiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Salazar-Meyers
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Williamsburgh, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           English as a second language teacher
          </h2>
          <h3 class="subtitle is-6 company">
           Parker, Murphy and Brooks
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Mitchellburgh, AE
         </p>
         <p class="is-small has-text-grey">

a. Use the .find method to find the tag containing the first job title ("Senior Python Developer"). Hint: can you find a tag type and/or a class that could be helpful for extracting this information? Extract the text from this title.

In [13]:
soup.find('h2').text

'Senior Python Developer'

b. Now, use what you did for the first title, but extract the job title for all jobs on this page. Store the results in a list.

In [23]:
job_titles = [x.get_text() for x in soup.find_all('h2')]

c. Finally, extract the companies, locations, and posting dates for each job. For example, the first job has a company of "Payne, Roberts and Davis", a location of "Stewartbury, AA", and a posting date of "2021-04-08". Ensure that the text that you extract is clean, meaning no extra spaces or other characters at the beginning or end.

In [26]:
companies = [x.get_text() for x in soup.find_all('h3', attrs={'class': 'company'})]

In [32]:
locations = [x.get_text().strip() for x in soup.find_all('p', class_='location')]

In [35]:
posting_dates = [x.get_text().strip() for x in soup.find_all('time')]

d. Take the lists that you have created and combine them into a pandas DataFrame.

In [37]:
jobs_info = pd.DataFrame({'job_title':job_titles, 'company':companies, 'location':locations, 'posting_date':posting_dates})

In [38]:
jobs_info

,job_title,company,location,posting_date
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08
...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08

2. Next, add a column that contains the url for the "Apply" button. Try this in two ways.
   <br>a. First, use the BeautifulSoup find_all method to extract the urls.

In [39]:
soup.find_all('a')

[<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/surgeon-16.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/newspaper-journalist-18.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/materials-engineer-19.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-process-development-scientist-21.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/ecologist-23.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/materials-engineer-24.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/historic-buildings-inspector-conservation-officer-25.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/data-scientist-26.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/psychiatrist-27.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/structural-engineer-28.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/immigration-officer-29.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/neurosurgeon-31.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/broadcast-engineer-32.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/make-33.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/nurse-adult-34.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/air-broker-35.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/editor-film-video-36.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/production-assistant-radio-37.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-communications-38.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/sales-executive-39.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/futures-trader-41.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/tour-manager-42.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/cytogeneticist-43.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/designer-multimedia-44.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/trade-union-research-officer-45.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chemist-analytical-46.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/programmer-multimedia-47.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-broadcasting-operations-48.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/teacher-primary-school-49.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-developer-50.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-51.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/producer-television-film-video-52.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/scientist-forensic-53.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/bonds-trader-54.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/editorial-assistant-55.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/photographer-56.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/retail-banker-57.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/jewellery-designer-58.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/ophthalmologist-59.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/licensed-conveyancer-61.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/futures-trader-62.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/counselling-psychologist-63.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/insurance-underwriter-64.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-automotive-65.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/producer-radio-66.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/dispensing-optician-67.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/designer-fashion-clothing-68.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chartered-loss-adjuster-69.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/forest-woodland-manager-71.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/clinical-cytogeneticist-72.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/print-production-planner-73.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/systems-developer-74.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/graphic-designer-75.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/writer-76.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/field-seismologist-77.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chief-strategy-officer-78.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/air-cabin-crew-79.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/warden-ranger-81.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/sports-therapist-82.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/arts-development-officer-83.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/printmaker-84.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/health-and-safety-adviser-85.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-86.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/programmer-applications-87.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,

In [45]:
apply_links = [x.get('href') for x in soup.find_all('a') if x.get_text() == 'Apply']

b. Next, get those same urls in a different way. Examine the urls and see if you can spot the pattern of how they are constructed. Then, build the url using the elements you have already extracted. Ensure that the urls that you created match those that you extracted using BeautifulSoup. Warning: You will need to do some string cleaning and prep in constructing the urls this way. For example, look carefully at the urls for the "Software Engineer (Python)" job and the "Scientist, research (maths)" job.

In [46]:
url_start = 'https://realpython.github.io/fake-jobs/jobs/'

In [64]:
re.sub(r'[\(\),]', '', jobs_info.loc[70, 'job_title'].lower()).split(' ')

['back-end', 'web', 'developer', 'python', 'django']

In [72]:
apply_links_alt = []
for i, row in jobs_info.iterrows():
    url_suffix = re.sub(r'[\(\),]', '', row['job_title'].lower())
    url_suffix = re.sub(r'/', ' ', url_suffix).split(' ')
    url_suffix.append(str(i))
    url_suffix = '-'.join(url_suffix)
    apply_links_alt.append(url_start + url_suffix + '.html')

In [75]:
apply_links_alt == apply_links

True

In [86]:
jobs_info['url'] = apply_links

In [87]:
jobs_info.head()

,job_title,company,location,posting_date,url
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...

3. Finally, we want to get the job description text for each job.
    <br>a. Start by looking at the page for the first job, https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html. Using BeautifulSoup, extract the job description paragraph.

In [76]:
response_job_1 = requests.get('https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html', headers=headers)

In [78]:
soup_job_1 = bs(response_job_1.text)

In [80]:
print(soup_job_1.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fake Python
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
 </head>
 <body>
  <section class="section">
   <div class="container mb-5">
    <h1 class="title is-1">
     Fake Python
    </h1>
    <p class="subtitle is-3">
     Fake Jobs for Your Web Scraping Journey
    </p>
   </div>
   <div class="container">
    <div class="columns is-multiline" id="ResultsContainer">
     <div class="box">
      <h1 class="title is-2">
       Senior Python Developer
      </h1>
      <h2 class="subtitle is-4 company">
       Payne, Roberts and Davis
      </h2>
      <div class="content">
       <p>
        Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.
       </p>
       <p id="location">
        <strong>
         Location:
        </strong>
        Stewartbury, AA
       </p>
       <p id="date">
        <strong>
         Posted:
        </strong>
        2021-04-08
       </p>
      </div>
     </div>
    </div>
   </div>
  </section>
 </body>
</html>

In [83]:
soup_job_1.find(class_='content').find('p').get_text()

'Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.'

b. We want to be able to do this for all pages. Write a function which takes as input a url and returns the description text on that page. For example, if you input "https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" into your function, it should return the string "At be than always different American address. Former claim chance prevent why measure too. Almost before some military outside baby interview. Face top individual win suddenly. Parent do ten after those scientist. Medical effort assume teacher wall. Significant his himself clearly very. Expert stop area along individual. Three own bank recognize special good along.".

In [84]:
def get_job_description(url):
    response_job = requests.get(url, headers=headers)
    soup_job = bs(response_job.text)
    description = soup_job.find(class_='content').find('p').get_text()
    return description

In [85]:
get_job_description('https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html')

'At be than always different American address. Former claim chance prevent why measure too. Almost before some military outside baby interview. Face top individual win suddenly. Parent do ten after those scientist. Medical effort assume teacher wall. Significant his himself clearly very. Expert stop area along individual. Three own bank recognize special good along.'

c. Use the .apply method on the url column you created above to retrieve the description text for all of the jobs.

In [89]:
jobs_info['description'] = jobs_info['url'].apply(get_job_description)

In [90]:
jobs_info.head()

,job_title,company,location,posting_date,url,description
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...,Professional asset web application environment...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...,Party prevent live. Quickly candidate change a...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...,Administration even relate head color. Staff b...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...,Tv program actually race tonight themselves tr...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...,Traditional page a although for study anyone. ...